In [1]:
pip install numpy


In [2]:
pip install tensorflow

In [3]:
import numpy as np
import tensorflow as tf
np.__version__


'2.0.2'

In [4]:
np.array([1,2,3])


array([1, 2, 3])

In [6]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.random.randint(10,100,(4,10),int)

array([[92, 12, 75, 19, 28, 54, 96, 95, 88, 24],
       [41, 61, 89, 10, 34, 22, 99, 22, 69, 25],
       [49, 85, 51, 29, 85, 31, 86, 79, 25, 57],
       [55, 28, 10, 52, 12, 67, 63, 56, 33, 78]])

In [20]:
np.random.normal(22,5,(3,4))

array([[18.5184973 , 10.06309308, 25.91060233, 21.68718145],
       [14.80920513, 18.5219848 , 12.13943281, 15.02220279],
       [21.9349852 , 20.781477  , 22.6696471 , 20.50464349]])

In [31]:
x1= np.random.randint(10,size=6)
x2= np.random.randint(10,size=(3,4))
x3= np.random.randint(10,size=(3,4,5))
x3  # number of 2d matrices,rows,columns

array([[[5, 3, 2, 6, 0],
        [0, 9, 5, 3, 4],
        [2, 4, 0, 3, 7],
        [0, 5, 7, 0, 1]],

       [[3, 2, 1, 1, 8],
        [4, 3, 9, 1, 8],
        [7, 2, 6, 4, 6],
        [8, 3, 8, 6, 4]],

       [[4, 4, 5, 4, 1],
        [6, 9, 2, 8, 7],
        [8, 1, 6, 8, 0],
        [5, 9, 3, 3, 3]]])

In [35]:
x2

array([[3, 2, 5, 3],
       [2, 0, 6, 9],
       [9, 4, 2, 3]])

In [30]:
x1

array([8, 5, 8, 1, 3, 4])

In [33]:
x1[4:6]

array([0, 0])

In [40]:
x2[1::,1:3]

array([[0, 6],
       [4, 2]])

In [37]:
x2[-1,-1]

np.int64(3)

In [47]:
x1.ndim

1

In [44]:
x3.shape

(3, 4, 5)

In [46]:
x2.ndim

2

In [48]:
x2_a=np.random.randint(10,size=(3,4))


In [52]:
mymat=x2+x2_a
mymat

array([[ 6, 11,  6, 10],
       [ 3,  5, 13, 18],
       [14,  4, 10,  9]])

In [53]:
mymat.sum
mymat.max
mymat.min


<function ndarray.min>